version: "3.5"
services:
    app:
      build: .
      ports: 
        - "8080:8080"
      links: 
        - db
      depends_on: 
        - db

    db:
      image: mysql:8.0.22
      container_name: mysqlDB
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DB}
      command: --init-file /data/application/init.sql
      volumes:
          - ./sql/sqlschema.sql:/data/application/init.sql
          - db_data:/var/lib/mysql
      restart: always
volumes:
    db_data: