version: "3.5"
services:
    swag:
      image: ghcr.io/linuxserver/swag
      container_name: swag
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - URL=${DOMAIN}
        - SUBDOMAINS=www,
        - VALIDATION=http
      volumes:
        - /proxy:/config
      ports:
        - 443:443
        - 80:80 
      restart: unless-stopped

    app:
      build: .
      container_name: hangman
      links: 
        - db
      depends_on: 
        - db
        - swag
      restart: always

    db:
      image: mysql:8.0.22
      container_name: mysqlDB
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DB}
      command: --init-file /data/application/init.sql
      volumes:
          - ./sql/sqlschema.sql:/data/application/init.sql
          - db_data:/var/lib/mysql
      restart: always

volumes:
    db_data: